package com.springdatajpa.entities;

import javax.persistence.*;

@Entity
@Table(name = "EMPLOYEE")
public class Employee {

	
	/* 1. Indentity
	 * Oracle Does not suppot generator type Identity
	 
	 @GeneratedValue(strategy = GenerationType.IDENTITY) 
	 */
	
	/* 
	 * 2. Table Generator:- 
	 * name = name of the table generator
	 * table = generator id table name
	 * pkColumnName = primary key column in id_gen table which stores sequence name
	 * valueColumnName = value column in id_gen table which stores the value generated by hibernate
	 * allocationSize = id increament by
	
	 @TableGenerator(name = "employee_gen", table = "ID_GEN", pkColumnName = "GEN_NAME", valueColumnName = "GEN_VALUE", allocationSize = 1)
	 @GeneratedValue(strategy = GenerationType.TABLE, generator = "employee_gen")
	 */	
	
	/*
	 *3. RandomCustomeIdGenerator:
	 
	@GenericGenerator(name = "emp_id", strategy = "com.springdatajpa.CustomeRandomIdGenerator")
	@GeneratedValue(generator = "emp_id") 
	 */
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private long id;
	private String name;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
